### ISSUE TITLE
Plugin approvals

### ISSUE THREAD

**Issue by NyakudyaA** [ENVI-coding/geodata2ENVI-met#1]
#Problem

Can you please change the link for the issue tracker to point the issue tracker here

**Comment by NyakudyaA** [comment]
ping @AntonelloDN

**Comment by helge-simon** [comment]
Sry @NyakudyaA I didn't see your post - I changed the issue tracker to here

**Comment by NyakudyaA** [comment]
you need to upload a new plugin with the updated metadata.txt so that I can approve

**Comment by helge-simon** [comment]
Thanks @NyakudyaA! Before, I only changed it in the zip - it is now also updated in the metadata
