### ISSUE TITLE
Buildings at border not removed

### ISSUE THREAD

**Issue by ElyumOfTheRocks** [ENVI-coding/geodata2ENVI-met#3]
Hello !

There seems to be a bug with the function that removes building block from borders. When I change it in the gui, the removed number of cells stays at default (5 grid cells removed).

However, if I manually change that number both at lines 202 and 2747 in geodata2ENVImet.py in the plugin files, I get to remove the number of grid cells that I want. 

I am no python expert, so I don't undestand perfectly your code, but maybe that bit of investigation will help.

Best,
E

**Comment by helge-simon** [comment]
Hello! 
Thanks I found the bug, the value in the GUI was never used in the acutal code...
Abou the model rotation: It is now fixed, the lower edge of the ENVI-met model area will always be defined by the first two points of the rectangle of the sub area. The easiest tool to create the rectangle is by using the "Add Rectangle from 3 Points" tool.

Thank you so much for reporting the issues!!!

Best
Helge

**Comment by ElyumOfTheRocks** [comment]
My pleasure! Thanks for addressing them so quickly too. 
I was wondering, how long does it take usually for the changes to go in the QGIS repositories?

Best,
E

**Comment by helge-simon** [comment]
If only I knew... What you can always do is download the repository as a ZIP and install the plugin from zip in QGIS.
Best
Helge

**Comment by ElyumOfTheRocks** [comment]
Good idea, I might try that 

For now I just added "self.dlg.se_bBorders.value()" at line 2747 in my installation, it's working well!

Have very nice day!
E
