### ISSUE TITLE
Cannot generate buildings with layer's height attribute

### ISSUE THREAD

**Issue by sfaraut** [ENVI-coding/geodata2ENVI-met#5]
Hi!

We would like to use the QGIS plugin with data from the data of the French institute IGN (BDTOPO V3), using in particular building's height informations.
But we have a problem...
It seems that building's heigh attribute of building layer is not taken in account and the plugin generate no corresponding INX data.
When we use static value for building height, data seems to bee generated correctly (see screenshots below).
As proposed, we used UTM coordinate system for building and zone layers (EPSG:32631 - WGS 84 / UTM zone 31N - Projected).
Could you please give us direction/guide/advise to make this works? Or could it be a bug with our Windows 10 environment (French language)?
Thanks by advance.
Regards.
Serge Faraut.

**Comment by sfaraut** [comment]
For illustration, here is the QGIS project's screen shot, of a small area of our urban studies:
![2023-05-17 10_50_16-DATA-SIG-Colomiers-ENVI-MET-UTM-v01-screenshot](https://github.com/ENVI-coding/geodata2ENVI-met/assets/4488885/5189b883-6c21-4709-8abf-905aaf5f3286)

**Comment by helge-simon** [comment]
Hi Serge,

sorry for the late reply! I just tested it - it worked for me. I think the problem could be, that you selected "fid" as building bottom. Instead, you should have not selected anything and used the "use static value instead" option with "0" as value.

<img width="629" alt="image" src="https://github.com/ENVI-coding/geodata2ENVI-met/assets/72987877/30e4a84b-1e38-4ab8-bfae-4b3c1408ab7f">

That way I was able to generate this model area:
<img width="806" alt="image" src="https://github.com/ENVI-coding/geodata2ENVI-met/assets/72987877/994e170d-bebd-4222-a821-fb8f92d005bb">

Best
Helge
