### ISSUE TITLE
qgis crash when selecting aoi and dem

### ISSUE THREAD

**Issue by idheitmann** [ENVI-coding/geodata2ENVI-met#6]
An error has occurred while executing Python code:
             
             
[OAK_A_Raster.zip](https://github.com/ENVI-coding/geodata2ENVI-met/files/13059044/OAK_A_Raster.zip)

             IndexError: index 301 is out of bounds for axis 1 with size 300
             
             
             Traceback (most recent call last):
              File "C:\Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geodata2envimet\Worker.py", line 2060, in calc_vert_ext
              self.getDEM() # self.maxHeightDEM is now filled
              File "C:\Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geodata2envimet\Worker.py", line 1258, in getDEM
              if grid1_int_array[i, j + srchRad] != -999:
             IndexError: index 301 is out of bounds for axis 1 with size 300
             
             
             
             
             Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
             
             
             QGIS version: 3.32.3-Lima Lima, 67d46100b5
             
             
             Python Path:
             
             C:\Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UMEP\SUEWSPrepare/ModulesC:\Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\processing_umepC:\Users\ivan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\planet_explorer\extlibsC:/OSGeo4W/apps/qgis/./pythonC:/Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:/Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/pluginsC:/OSGeo4W/apps/qgis/./python/pluginsC:\OSGeo4W\apps\grass\grass83\etc\pythonC:\Users\ivan\DocumentsC:\OSGeo4W\bin\python39.zipC:\OSGeo4W\apps\Python39\DLLsC:\OSGeo4W\apps\Python39\libC:\OSGeo4W\binC:\Users\ivan\AppData\Roaming\Python\Python39\site-packagesC:\OSGeo4W\apps\Python39C:\OSGeo4W\apps\Python39\lib\site-packagesC:\OSGeo4W\apps\Python39\lib\site-packages\win32C:\OSGeo4W\apps\Python39\lib\site-packages\win32\libC:\OSGeo4W\apps\Python39\lib\site-packages\PythonwinC:/Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/pythonC:\Users\ivan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/formsC:\Users/ivan/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2webC:\Users\ivan\AppData\Roaming\QGIS\QGIS3\profiles\default\python\pluginsD:/Geospatial.local/West_Oakland/OAK_C_Maps

**Comment by helge-simon** [comment]
Hi,

thanks for the feedback. Can you try with a raster that is slightly larger? I assume the jagged edges of the raster (due to the rotated vector) are causing the issue

Best
Helge

**Comment by idheitmann** [comment]
I clipped the raster to the AOI only to make it easier to upload... the source is actually much much larger. It crashes every time. Here I am sharing a larger section of the raster.
I am using 2m grid spacing.
[WO_DEM3ft_26910_clip_m.zip](https://github.com/ENVI-coding/geodata2ENVI-met/files/13284096/WO_DEM3ft_26910_clip_m.zip)

**Comment by idheitmann** [comment]
sorry do you think you could reopen this issue? it's pretty critical to either figure out how to work-around or fix this persistent crash for us

**Comment by helge-simon** [comment]
Yes, of course! I closed the issue as I thought it was sloved after not having heard back from you.
I will try to get it fixed

**Comment by helge-simon** [comment]
@idheitmann Please download the plugin again from the repository. I am positive I found the issue.
